# ----------------
# Window rules 
# ----------------

# Browsers -> tile
windowrule = tile on, match:title = ^Microsoft-edge$
windowrule = tile on, match:title = ^Brave-browser$
windowrule = tile on, match:title = ^Chromium$

# Utility apps -> float
windowrule {
    name = blueman-manager
    match:initial_class = .blueman-manager-wrapped
    match:initial_title = Bluetooth Devices
    float = 1
    size = 800 600
    center = 1
}

windowrule {
    name = waypaper-float
    match:initial_class = ^waypaper$
    float = 1
    size = 800 600
    center = 1
}

windowrule = float on, match:title = ^pavucontrol$
windowrule = float on, match:title = ^nm-connection-editor$
windowrule = float on, match:title = ^qalculate-gtk$

# Browser Picture-in-Picture
windowrule = float on, match:title = ^Picture-in-Picture$
windowrule = pin on, match:title = ^Picture-in-Picture$

# Workspace placement
windowrule = workspace 5, match:class = ^mpv$
windowrule = workspace 5, match:class = ^kitty$, match:title = ^RMPC$
windowrule = opacity 0.8 0.8, match:class = ^org.gnome.Nautilus$
windowrule = opacity 0.8 0.8, match:class = ^kitty$
